<?php

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

$now = Carbon::now();

$cursos = [
    [
        'titulo'     => 'Gestão e Planejamento de Operações Minerais',
        'descricao'  => 'Princípios de gestão aplicados a operações de mineração: planeamento de produção, controlo de custos, gestão de pessoas e indicadores KPI.',
        'nivel'      => 'Avançado',
        'duracao'    => '3 meses',
        'modalidade' => 'Online / Presencial',
        'preco_usd'  => '$3,000',
        'preco_aoa'  => 'AKZ 2,400,000',
        'cor'        => '#1a3a5c',
        'topicos'    => json_encode(['Planeamento de lavra', 'Controlo de produção', 'Gestão de pessoas', 'Indicadores KPI', 'Segurança operacional']),
        'ativo'      => 1,
        'ordem'      => 1,
        'created_at' => $now,
        'updated_at' => $now,
    ],
    [
        'titulo'     => 'Engenharia de Beneficiamento Mineral',
        'descricao'  => 'Técnicas de separação física e química de minerais. Projecto e operação de circuitos de flotação, moagem e classificação.',
        'nivel'      => 'Avançado',
        'duracao'    => '3 meses',
        'modalidade' => 'Presencial (Luanda)',
        'preco_usd'  => '$2,500',
        'preco_aoa'  => 'AKZ 2,000,000',
        'cor'        => '#c9922a',
        'topicos'    => json_encode(['Britagem e moagem', 'Flotação mineral', 'Separação magnética', 'Filtragem e secagem', 'Controlo de qualidade']),
        'ativo'      => 1,
        'ordem'      => 2,
        'created_at' => $now,
        'updated_at' => $now,
    ],
    [
        'titulo'     => 'Geoprocessamento e Modelagem 3D',
        'descricao'  => 'Uso de softwares modernos (Leapfrog, Vulcan, MapInfo) para modelagem geológica, estimativa de recursos e planeamento mineiro.',
        'nivel'      => 'Intermédio',
        'duracao'    => '2 meses',
        'modalidade' => 'Online',
        'preco_usd'  => '$1,800',
        'preco_aoa'  => 'AKZ 1,440,000',
        'cor'        => '#0d8a7d',
        'topicos'    => json_encode(['Leapfrog Geo', 'Modelagem geológica 3D', 'Estimativa de recursos', 'Mapas e SIG', 'Relatórios JORC']),
        'ativo'      => 1,
        'ordem'      => 3,
        'created_at' => $now,
        'updated_at' => $now,
    ],
    [
        'titulo'     => 'Automação e Controle de Processos Minerais',
        'descricao'  => 'Introdução à automação industrial aplicada à mineração: PLCs, SCADA, sensores e controlo de circuitos de processamento.',
        'nivel'      => 'Intermédio',
        'duracao'    => '2 meses',
        'modalidade' => 'Online / Presencial',
        'preco_usd'  => '$2,000',
        'preco_aoa'  => 'AKZ 1,600,000',
        'cor'        => '#1a3a5c',
        'topicos'    => json_encode(['PLCs e SCADA', 'Instrumentação industrial', 'Controlo de circuitos', 'Manutenção preditiva', 'IoT na mineração']),
        'ativo'      => 1,
        'ordem'      => 4,
        'created_at' => $now,
        'updated_at' => $now,
    ],
    [
        'titulo'     => 'Segurança e Meio Ambiente em Mineração',
        'descricao'  => 'Legislação angolana e normas internacionais de SST e meio ambiente. Gestão de riscos, planos de emergência e impacto ambiental.',
        'nivel'      => 'Básico',
        'duracao'    => '1 mês',
        'modalidade' => 'Online',
        'preco_usd'  => '$1,000',
        'preco_aoa'  => 'AKZ 800,000',
        'cor'        => '#c9922a',
        'topicos'    => json_encode(['Legislação angolana SST', 'Avaliação de riscos', 'Planos de emergência', 'Gestão ambiental', 'Licenciamento']),
        'ativo'      => 1,
        'ordem'      => 5,
        'created_at' => $now,
        'updated_at' => $now,
    ],
    [
        'titulo'     => 'Prospecção e Avaliação de Depósitos Minerais',
        'descricao'  => 'Métodos de prospeção geofísica, geoquímica e por sondagem. Avaliação económica de depósitos e modelos de recursos.',
        'nivel'      => 'Intermédio',
        'duracao'    => '2 meses',
        'modalidade' => 'Online / Presencial',
        'preco_usd'  => '$1,500',
        'preco_aoa'  => 'AKZ 1,200,000',
        'cor'        => '#0d8a7d',
        'topicos'    => json_encode(['Geofísica aplicada', 'Geoquímica de prospeção', 'Sondagem e amostragem', 'Modelos de recursos', 'Análise económica']),
        'ativo'      => 1,
        'ordem'      => 6,
        'created_at' => $now,
        'updated_at' => $now,
    ],
];

DB::table('cursos')->insert($cursos);
echo DB::table('cursos')->count() . ' cursos inseridos';
